name: Post Daily Tech News

on:
  schedule:
    # Runs 3 times a day: 8AM, 2PM, 8PM EAT (adjust UTC by -3 hours)
    - cron: "0 5 * * *" # 5:00 UTC = 8:00 AM EAT
    - cron: "0 11 * * *" # 11:00 UTC = 2:00 PM EAT
    - cron: "0 17 * * *" # 17:00 UTC = 8:00 PM EAT
  workflow_dispatch: # Allows manual triggering from GitHub UI for testing

jobs:
  post-news:
    runs-on: ubuntu-latest # Free Linux runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Clones your repo

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the poster script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          GROUP_ID: ${{ secrets.GROUP_ID }} # Or numeric ID like -1001234567890
        run: python daily_poster.py
